import Foundation
import RFCKit

/// Converts one legacy plain-text RFC to RFCXML: parse, apply the index's metadata,
/// serialize, and check the output parses back. The same call for a corpus run and for
/// a test, and it touches no file: reading the text and writing the XML are the
/// caller's.
public struct DocumentConverter: Sendable {
  /// Whether to put every block to the prose test and report its verdict. Diagnosing
  /// re-segments the document, which roughly doubles a run.
  public var diagnosesProse: Bool
  /// Whether to count the lines dropped as page furniture into the report.
  public var countsFurniture: Bool
  /// Whether to collect the blocks on the prose test's decision boundary. Diagnosing
  /// costs what `diagnosesProse` does, once for both.
  public var samplesBoundary: Bool

  public init(
    diagnosesProse: Bool = false, countsFurniture: Bool = false, samplesBoundary: Bool = false
  ) {
    self.diagnosesProse = diagnosesProse
    self.countsFurniture = countsFurniture
    self.samplesBoundary = samplesBoundary
  }

  /// Why a document is not converted, as `report.json` records it.
  public enum Skip: String, Sendable {
    /// The text only says where the RFC's PDF or PostScript original is (#316): RFC
    /// 570, 1119, 1124, 1128, 1129 and 1131. Converted, it is a document with nothing
    /// in it, which the schema refuses for two of them and takes for the other four; a
    /// section saying where the original is would be words the RFC does not have. The
    /// app opens the original instead, by the same test (`PublishedOriginal`, #207).
    case publishedOnlyAsPDF = "published-only-as-pdf"
  }

  /// One converted document.
  public struct Conversion: Sendable {
    /// Nil when the document is skipped, and the report says why.
    public var xml: Data?
    /// Without `schema`, which takes xmllint and so is the caller's to fill in.
    public var report: DocumentReport
    /// Nil unless `diagnosesProse`.
    public var prose: ProseReport?
    /// Nil unless `samplesBoundary`. `unlocated` counts the blocks on the boundary that
    /// could not be found in the source; it goes to the run's log, not the report, so the
    /// report reads the same with or without the sample.
    public var boundary: BoundarySample.Sample?
  }

  /// Converts the text of the document `stem` (`rfc2119`, from `rfc2119.txt`).
  ///
  /// `metadata` is the RFC index's entry for it, where the run has an index: the RFC
  /// Editor's own record of each document's title, number, authors and date, and of
  /// what it obsoletes and updates, which a title page states less reliably than
  /// anything else in the document (#170, #171, #218). See `IndexHeader`.
  public func convert(text: String, stem: String, metadata: RFCMetadata?) -> Conversion {
    var document = LegacyTextParser.parse(text, title: metadata?.title)
    if let skip = Self.skip(document, stem: stem, metadata: metadata) {
      var report = DocumentReport(document: document, id: stem, overridden: false)
      // What a document with nothing in it warns about says nothing of a skipped one.
      report.warnings = []
      report.skipped = skip.rawValue
      return Conversion(xml: nil, report: report)
    }
    let notes = metadata.map { IndexHeader.apply($0, to: &document.header) } ?? []
    // Diagnosed once for both reports.
    let blocks =
      diagnosesProse || samplesBoundary
      ? LegacyTextParser.proseDiagnostics(for: text, title: metadata?.title) : []
    let prose = diagnosesProse ? ProseReport(diagnosed: blocks, id: stem) : nil
    let boundary =
      samplesBoundary ? BoundarySample.entries(for: blocks, in: text, document: stem) : nil
    let sourceURL = DocumentID(parsing: stem).map { RFCEditorEndpoints.document($0, format: .text) }
    let serializer = RFCXMLSerializer(
      options: .init(
        generatorComment:
          "Generated by rfc-reader corpus-build from \(stem).txt. Structure recovered heuristically from the plain-text RFC; the text itself is unchanged. Corrections: https://github.com/Radiergummi/rfc-reader",
        sourceURL: sourceURL
      ))
    let serialization = serializer.serialization(of: document)
    let xml = Data(serialization.xml.utf8)

    var report = DocumentReport(document: document, id: stem, overridden: false)
    report.warnings += notes
    report.warnings += serialization.warnings
    if countsFurniture { report.furniture = LegacyTextParser.recurringFurniture(in: text).count }
    // Round-trip check: the XML must parse back into the same section tree.
    do {
      let reparsed = try RFCXMLParser.parse(xml)
      if reparsed.allSections.count != document.allSections.count {
        report.warnings.append(
          "round trip changed section count \(document.allSections.count) → \(reparsed.allSections.count)"
        )
      }
    } catch {
      report.warnings.append("generated XML does not parse: \(error)")
    }
    return Conversion(xml: xml, report: report, prose: prose, boundary: boundary)
  }

  /// Why `document`, parsed from the text of `stem`, is not converted, if it is not.
  /// Only a run with an index can tell: whether the RFC has an original is the index's
  /// to say.
  public static func skip(_ document: RFCDocument, stem: String, metadata: RFCMetadata?)
    -> Skip?
  {
    guard let metadata, let id = DocumentID(parsing: stem),
      PublishedOriginal(id, formats: metadata.formats, text: document) != nil
    else { return nil }
    return .publishedOnlyAsPDF
  }
}
