import Foundation
import RFCKit

/// Converts one legacy plain-text RFC to RFCXML: parse, apply the index's metadata,
/// serialize, and check the output parses back. The same call for a corpus run and for
/// a test, and it touches no file: reading the text and writing the XML are the
/// caller's.
public struct DocumentConverter: Sendable {
  /// Whether to put every block to the prose test and report its verdict. Diagnosing
  /// re-segments the document, which roughly doubles a run.
  public var diagnosesProse: Bool
  /// Whether to count the lines dropped as page furniture into the report.
  public var countsFurniture: Bool

  public init(diagnosesProse: Bool = false, countsFurniture: Bool = false) {
    self.diagnosesProse = diagnosesProse
    self.countsFurniture = countsFurniture
  }

  /// One converted document.
  public struct Conversion: Sendable {
    public var xml: Data
    /// Without `schema`, which takes xmllint and so is the caller's to fill in.
    public var report: DocumentReport
    /// Nil unless `diagnosesProse`.
    public var prose: ProseReport?
  }

  /// Converts the text of the document `stem` (`rfc2119`, from `rfc2119.txt`).
  ///
  /// `metadata` is the RFC index's entry for it, where the run has an index: the RFC
  /// Editor's own record of each document's title and of what it obsoletes and updates,
  /// which a title page states less reliably than anything else in the document
  /// (#170, #171).
  public func convert(text: String, stem: String, metadata: RFCMetadata?) -> Conversion {
    var document = LegacyTextParser.parse(text, title: metadata?.title)
    if let metadata {
      document.header.obsoletes = metadata.obsoletes
      document.header.updates = metadata.updates
    }
    let prose =
      diagnosesProse ? ProseReport(diagnosing: text, id: stem, title: metadata?.title) : nil
    let sourceURL = DocumentID(parsing: stem).map { RFCEditorEndpoints.document($0, format: .text) }
    let serializer = RFCXMLSerializer(
      options: .init(
        generatorComment:
          "Generated by rfc-reader corpus-build from \(stem).txt. Structure recovered heuristically from the plain-text RFC; the text itself is unchanged. Corrections: https://github.com/Radiergummi/rfc-reader",
        sourceURL: sourceURL
      ))
    let serialization = serializer.serialization(of: document)
    let xml = Data(serialization.xml.utf8)

    var report = DocumentReport(document: document, id: stem, overridden: false)
    report.warnings += serialization.warnings
    if countsFurniture { report.furniture = LegacyTextParser.recurringFurniture(in: text).count }
    // Round-trip check: the XML must parse back into the same section tree.
    do {
      let reparsed = try RFCXMLParser.parse(xml)
      if reparsed.allSections.count != document.allSections.count {
        report.warnings.append(
          "round trip changed section count \(document.allSections.count) → \(reparsed.allSections.count)"
        )
      }
    } catch {
      report.warnings.append("generated XML does not parse: \(error)")
    }
    return Conversion(xml: xml, report: report, prose: prose)
  }
}
