import Foundation
import RFCKit

#if canImport(FoundationXML)
  import FoundationXML
#endif

/// Converts one legacy plain-text RFC to RFCXML: parse, apply the index's metadata,
/// serialize, apply the document's patch where it has one, and check that the output
/// is what parsing and writing it again gives. The same call for a corpus run and for
/// a test, and it touches no file: reading the text and writing the XML are the
/// caller's.
public struct DocumentConverter: Sendable {
  /// Whether to put every block to the prose test and report its verdict. Diagnosing
  /// re-segments the document, which roughly doubles a run.
  public var diagnosesProse: Bool
  /// Whether to count the lines dropped as page furniture into the report.
  public var countsFurniture: Bool
  /// Whether to collect the blocks on the prose test's decision boundary. Diagnosing
  /// costs what `diagnosesProse` does, once for both.
  public var samplesBoundary: Bool

  public init(
    diagnosesProse: Bool = false, countsFurniture: Bool = false, samplesBoundary: Bool = false
  ) {
    self.diagnosesProse = diagnosesProse
    self.countsFurniture = countsFurniture
    self.samplesBoundary = samplesBoundary
  }

  /// One converted document.
  public struct Conversion: Sendable {
    /// Nil when the document is skipped, and the report says why.
    public var xml: Data?
    /// Without `schema`, which takes xmllint and so is the caller's to fill in.
    public var report: DocumentReport
    /// Nil unless `diagnosesProse`.
    public var prose: ProseReport?
    /// Nil unless `samplesBoundary`. `unlocated` counts the blocks on the boundary that
    /// could not be found in the source; it goes to the run's log, not the report, so the
    /// report reads the same with or without the sample.
    public var boundary: BoundarySample.Sample?
  }

  /// Converts the text of the document `stem` (`rfc2119`, from `rfc2119.txt`).
  ///
  /// `metadata` is the RFC index's entry for it, where the run has an index: the RFC
  /// Editor's own record of each document's title, number, authors and date, and of
  /// what it obsoletes and updates, which a title page states less reliably than
  /// anything else in the document (#170, #171, #218). See `IndexHeader`.
  ///
  /// `patch` is its correction in `corpus/overrides/`, where it has one (#197). The
  /// patched document is parsed and written again, so its XML is the canonical one,
  /// and fails if that loses any of its text. A document whose patch fails has no
  /// XML, and its report says why.
  public func convert(
    text: String, stem: String, metadata: RFCMetadata?, patch: XMLPatch? = nil
  ) -> Conversion {
    var document = LegacyTextParser.parse(text, title: metadata?.title)
    let override: DocumentReport.Override? = patch == nil ? nil : .patch
    if let skip = Self.skip(document, metadata: metadata) {
      var report = DocumentReport(document: document, id: stem, override: override)
      // What a document with nothing in it warns about says nothing of a skipped one.
      report.warnings = []
      report.skipped = skip
      // Its patch would do nothing without a word said.
      if let patch {
        report.failure = "\(patch.name): the document is not converted (\(skip.rawValue))"
      }
      return Conversion(xml: nil, report: report)
    }
    let notes = metadata.map { IndexHeader.apply($0, to: &document.header) } ?? []
    // Diagnosed once for both reports.
    let blocks =
      diagnosesProse || samplesBoundary
      ? LegacyTextParser.proseDiagnostics(for: text, title: metadata?.title) : []
    let prose = diagnosesProse ? ProseReport(diagnosed: blocks, id: stem) : nil
    let boundary =
      samplesBoundary ? BoundarySample.entries(for: blocks, in: text, document: stem) : nil
    let sourceURL = DocumentID(parsing: stem).map { RFCEditorEndpoints.document($0, format: .text) }
    let source =
      patch.map { "\(stem).txt and patched by corpus/overrides/\($0.name)" } ?? "\(stem).txt"
    let serializer = RFCXMLSerializer(
      options: .init(
        generatorComment:
          "Generated by rfc-reader corpus-build from \(source). Structure recovered heuristically from the plain-text RFC; the text itself is unchanged. Corrections: https://github.com/Radiergummi/rfc-reader",
        sourceURL: sourceURL
      ))
    let serialization = serializer.serialization(of: document)
    var xml = Data(serialization.xml.utf8)

    if let patch {
      do {
        (document, xml) = try Self.apply(patch, to: xml, serializer: serializer)
      } catch {
        var report = DocumentReport(document: document, id: stem, override: override)
        report.failure = error.message
        return Conversion(xml: nil, report: report)
      }
    }

    var report = DocumentReport(document: document, id: stem, override: override)
    report.warnings += notes
    report.warnings += serialization.warnings
    if countsFurniture { report.furniture = LegacyTextParser.recurringFurniture(in: text).count }
    // What the app reads is what it would write: parsed and written again, the XML is
    // the same bytes (#683).
    do {
      let again = serializer.serialize(try RFCXMLParser.parse(xml))
      if Data(again.utf8) != xml {
        let line = Self.firstDifferingLine(String(decoding: xml, as: UTF8.self), again)
        report.warnings.append("round trip changes the XML at line \(line)")
      }
    } catch {
      report.warnings.append("generated XML does not parse: \(error)")
    }
    return Conversion(xml: xml, report: report, prose: prose, boundary: boundary)
  }

  /// Why a patch was not applied.
  struct PatchFailure: Error {
    var message: String
  }

  /// `patch` applied to the converter's `xml`, then parsed and written again by
  /// `serializer`, with the document that came of it.
  ///
  /// The document is loaded preserving whitespace, since artwork is significant to
  /// the space. Writing it again gives one canonical output whatever XML library
  /// applied the patch, and guards against a patch adding what the model cannot hold,
  /// which writing would otherwise drop without a word: the text of the patched tree
  /// and of the written XML must be the same words.
  static func apply(
    _ patch: XMLPatch, to xml: Data, serializer: RFCXMLSerializer
  ) throws(PatchFailure) -> (RFCDocument, Data) {
    do {
      let tree = try XMLDocument(data: xml, options: .nodePreserveWhitespace)
      try patch.apply(to: tree)
      let document = try RFCXMLParser.parse(tree.xmlData)
      let written = Data(serializer.serialize(document).utf8)
      let writtenTree = try XMLDocument(data: written, options: .nodePreserveWhitespace)
      if let divergence = Self.divergence(
        tree.rootElement()?.stringValue ?? "", writtenTree.rootElement()?.stringValue ?? "")
      {
        throw PatchFailure(message: "\(patch.name): writing it loses text, \(divergence)")
      }
      return (document, written)
    } catch let failure as PatchFailure {
      throw failure
    } catch let failure as XMLPatch.Failure {
      throw PatchFailure(message: failure.description)
    } catch {
      throw PatchFailure(message: "\(patch.name): \(error)")
    }
  }

  /// Where the words of `patched` and `written` part, or nil when they are the same.
  static func divergence(_ patched: String, _ written: String) -> String? {
    let patchedWords = patched.split(whereSeparator: \.isWhitespace)
    let writtenWords = written.split(whereSeparator: \.isWhitespace)
    guard patchedWords != writtenWords else { return nil }
    let index = zip(patchedWords, writtenWords).prefix { $0 == $1 }.count
    func words(_ all: [Substring]) -> String {
      all[index..<min(all.count, index + 6)].joined(separator: " ")
    }
    return "from word \(index + 1): “\(words(patchedWords))” became “\(words(writtenWords))”"
  }

  /// The first line, from 1, where `first` and `second`, which differ, part.
  static func firstDifferingLine(_ first: String, _ second: String) -> Int {
    let firstLines = first.split(separator: "\n", omittingEmptySubsequences: false)
    let secondLines = second.split(separator: "\n", omittingEmptySubsequences: false)
    return zip(firstLines, secondLines).prefix { $0 == $1 }.count + 1
  }

  /// Why `document`, parsed from the text `metadata` indexes, is not converted, if it
  /// is not. Only a run with an index can tell: whether the RFC has an original is the
  /// index's to say.
  public static func skip(_ document: RFCDocument, metadata: RFCMetadata?)
    -> Manifest.SkipReason?
  {
    guard let metadata,
      PublishedOriginal(metadata.id, formats: metadata.formats, text: document) != nil
    else { return nil }
    return .publishedOnlyAsPDF
  }
}
